# Control file for Travis CI (http://travis-ci.org)
# Must be located in the root directory of the Git repository.

sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

# commands to install dependencies
install:
  - python -c "import platform; print('Demonstration of incorrect distro returned by platform.linux_distribution():'); print(repr(platform.linux_distribution()))"
  - python -c "import pip, os; print('Site-packages directory of system Python:'); print(os.path.dirname(os.path.dirname(pip.__file__)))"
  - pip list
  - pip install --upgrade pip
  - python uninstall_pbr_on_py26.py
  - make clobber
  - pip list
  - make develop
  - pip list
  - python -c "import setuptools,os; print('Version of GitPython package:'); sp=os.path.dirname(os.path.dirname(setuptools.__file__)); print(open(sp+'/git/__init__.py','r').read())"

# TODO 2016-05 AM: Remove displaying of GitPython version, once GitPython 2.0.4 is released.

# commands to run builds & tests
script:
  - make check
  - make build
  - if [[ $(python -c "import sys; print('%s.%s'%sys.version_info[0:2])") != 2.6 ]]; then make builddoc; fi
  - make test

# TODO 2016-05 AM: Remove disabling of "make builddoc" for Python 2.6, once GitPython 2.0.4 is released.

