
environment:
  matrix:
    - PYTHON: C:\Python27
      PYTHON_VERSION: 2.7.8
      PYTHON_ARCH: 32

install:

  # Add Windows Registry entries for Python
  - reg ADD HKCU\Software\Python\PythonCore\2.7\InstallPath /ve /d "C:\Python27" /t REG_SZ /f
  - reg ADD HKLM\Software\Python\PythonCore\2.7\InstallPath /ve /d "C:\Python27" /t REG_SZ /f

  # Add Python
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  ## Install InnoSetup - disabled because it is not needed
  #- choco install -y InnoSetup
  #- set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

  ## Install pip - disabled because pip is already installed
  #- ps: (new-object System.Net.WebClient).Downloadfile('https://bootstrap.pypa.io/get-pip.py', 'C:\Users\appveyor\get-pip.py')
  #- ps: Start-Process -FilePath "C:\Python27\python.exe" -ArgumentList "C:\Users\appveyor\get-pip.py" -Wait -Passthru

  # Add CygWin
  - set PATH=C:\cygwin\bin;%PATH%

  # Examine the environment
  - dir C:\
  - cd
  - dir
  #- set

  # TODO: Install OS-level prereq packages:
  # - prereqs for pip install of lxml:
  #   - libxml2 from http://xmlsoft.org/sources/win32/
  #   - libxslt from http://xmlsoft.org/sources/win32/
  #   - zlib developer files from http://gnuwin32.sourceforge.net/packages/zlib.htm
  #   - libiconv developer files from http://gnuwin32.sourceforge.net/packages/libiconv.htm
  #     and copy libiconv.lib to iconv.lib in PCbuild.

  # Install tox
  - pip install tox==2.0.0

  # Verify that the commands used in tox.ini are available
  - tox --version
  - make --version
  - pip --version
  - python --version

  # Verify that the commands used in makefile are available
  - sh --version
  - bash --version
  - rm --version
  - mv --version
  #- mkdir --version
  - xargs --version
  - grep --version
  - sed --version
  - tar --version
  - find --version

build: false # Not a C# project, build stuff at the test step instead.

before_test:

test_script:
  # the actual test command is disabled for now.
  - echo tox -e pywin

